### ISSUE TITLE
Custom firmware?

### ISSUE THREAD

**Issue by dfsx1** [DanTLehman/orion_sc008ha#2]
Thanks for your repo, it helped me a lot :)

I have a Meari BULLET4S, with same HiSilicon HI3518ERNCV300 board.
https://fccid.io/2AG7C-BULLET4S
https://fccid.io/2AG7C-BULLET4S/Internal-Photos/Internal-Photos-4652314

I also gave up cracking the meari_c5 root password and messing with ppsMmcTool.txt.
With $3 AliExpress CH341A programmer (with 3.3v modification) I managed to successfully extract the firmware.
Unfortunately with a SOP8 test clip it could not read it, I had to desolder the QH64AHIG chip from the pcb.
Probably I needed certain CS/RESET/HOLD pins set high/low according to the datasheet.
https://lcsc.com/product-detail/Others_XMC-XM25QH64AHIG_C328461.html
https://datasheet.lcsc.com/szlcsc/1811072025_XMC-XM25QH64AHIG_C328461.pdf
But I'll mess with this later, at least now I have a backup :)

I don't like the Tuya firmware and just want to access RTSP locally.
Most promising project I could find is OpenIPC.
https://openwrt.org/docs/techref/hardware/soc/soc.hisilicon.hi35xx
https://openipc.org/
http://alpha.openipc.org/firmware/
https://github.com/openipc
But it's only for Hi3518EV100/Hi3518EV200/Hi3516CV300/[..] not HI3518ERNCV300.

Datasheet specs for Hi3518EV200 and Hi3518EV300 are very different.
http://www.hisilicon.com/-/media/Hisilicon/pdf/Surveillance_mobilecam/Hi3518EV200.pdf
http://www.hisilicon.com/-/media/Hisilicon/pdf/Surveillance_mobilecam/Hi3518EV300.pdf

I see "Huawei LiteOS/Linux-4.9-based SDK" and found these Huawei/HiSilicon repositories.
But not sure if I can compile something useful from this.
https://github.com/OpenHarmony-mirror/vendor_hisi_hi35xx_hardware
https://github.com/OpenHarmony-mirror/vendor_hisi_hi35xx_hi35xx_init
https://github.com/OpenHarmony-mirror/vendor_hisi_hi35xx_hi3518ev300
https://github.com/OpenHarmony-mirror/vendor_hisi_hi35xx_hi3518ev300_uboot
https://github.com/OpenHarmony-mirror/vendor_hisi_hi35xx_middleware
https://github.com/OpenHarmony-mirror/vendor_hisi_hi35xx_middleware_source_third_party_ffmpeg
https://github.com/OpenHarmony-mirror/vendor_hisi_hi35xx_platform
https://github.com/OpenHarmony-mirror/vendor_hisi_hi35xx_thirdparty_uboot_src

Any ideas for other custom firmware or where to go from here?

**Comment by dfsx1** [comment]
Actually this HarmonyOs/OpenHarmony looks more promising than I initially thought!
Opensource and Hi3518 chip is from same manufacturer (Huawei/HiSilicon) anyway.
https://gitee.com/openharmony

Also found their tutorial specific for this Hi3518EV300 IP camera to "modify, compile, burn, and run Hello OHOS!".
https://device.harmonyos.com/en/docs/start/introduce/oem_camera_start_hi3518-0000001050170473
https://device.harmonyos.com/en/docs/start/introduce/oem_camera_start_environment-0000001052450997
https://device.harmonyos.com/en/docs/start/introduce/oem_camera_start_example-0000001051610926

The Hi3518EV300 dev-board in their pictures looks little bit different however (onboard sdcard?).

**Comment by dfsx1** [comment]
@nikitos1550 and your projects list hi3518ev300 hardware as supported under the hi3516ev200 family?

https://github.com/OpenHisiIpCam/wrt-hisicam
https://github.com/OpenHisiIpCam/br-hisicam

Or is it a typo?

**Comment by nikitos1550** [comment]
> @nikitos1550 and your projects list hi3518ev300 hardware as supported under the hi3516ev200 family?
> 
> https://github.com/OpenHisiIpCam/wrt-hisicam
> https://github.com/OpenHisiIpCam/br-hisicam
> 
> Or is it a typo?

hi3518ev300 is chip in family that we call hi3516ev200, mostly similar SoCs, some difference in RAM and peripheral. I don`t remember exactly. SDK is shared between these two chips.

**Comment by DeltaTangoLima** [comment]
Sorry for the lack of response here - life got in the way for a while.  Take a look at my updates - a fella by the name of Wagner managed to get a software hack working on these devices, which ultimately led to success getting RTSP working for me.
