### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by LouDnl** [DanTLehman/orion_sc008ha#3]
Hi, im working on a similar project with a different tuya camera and came to about the same point that you are. Do you have Discord so we can chat maybe?

**Comment by DeltaTangoLima** [comment]
Oh man - I'm so sorry for the lack of response here - life got in the way for a while. Take a look at my updates - a fella by the name of Wagner managed to get a software hack working on these devices, which ultimately led to success getting RTSP working for me.
